name: 'Automatic build'
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Change to Jekyll source directory
        run: cd hercules
        shell: bash

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Check baseurl
        working-directory: hercules
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "BASE_URL=$baseurl" >> $GITHUB_ENV
          fi
      - name: Build Site
        working-directory: hercules
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b -d "_site$BASE_URL"
      - name: Test Site
        working-directory: hercules
        run: |
          bash tools/test.sh
      - name: Deploy
        working-directory: hercules
        run: |
          if [[ -n $BASE_URL ]]; then
            mv _site$BASE_URL _site-rename
            rm -rf _site
            mv _site-rename _site
          fi
          bash tools/deploy.sh
